import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const INTERESTS = [
  { name: "Travel", icon: "plane" },
  { name: "Gaming", icon: "gamepad-2" },
  { name: "Fitness", icon: "dumbbell" },
  { name: "Movies", icon: "clapperboard" },
  { name: "Music", icon: "music" },
  { name: "Cooking", icon: "chef-hat" },
  { name: "Photography", icon: "camera" },
  { name: "Reading", icon: "book-open" },
  { name: "Coding", icon: "code" },
  { name: "Hiking", icon: "mountain" },
  { name: "Cycling", icon: "bike" },
  { name: "Coffee", icon: "coffee" },
  { name: "Dogs", icon: "dog" },
  { name: "Cats", icon: "cat" },
  { name: "Art", icon: "palette" },
  { name: "Dancing", icon: "music-2" },
  { name: "Anime", icon: "tv" },
  { name: "Football", icon: "trophy" },
  { name: "Cricket", icon: "target" },
  { name: "Basketball", icon: "circle" },
  { name: "Yoga", icon: "heart-pulse" },
  { name: "Technology", icon: "cpu" },
  { name: "Entrepreneurship", icon: "briefcase" },
  { name: "Fashion", icon: "shirt" },
  { name: "Food", icon: "utensils" },
  { name: "Nature", icon: "trees" },
  { name: "Swimming", icon: "waves" },
  { name: "Running", icon: "footprints" },
  { name: "Meditation", icon: "brain" },
  { name: "Wine", icon: "wine" },
  { name: "Beach", icon: "umbrella" },
  { name: "Camping", icon: "tent" },
  { name: "Skiing", icon: "snowflake" },
  { name: "Surfing", icon: "wind" },
  { name: "Golf", icon: "flag" },
  { name: "Tennis", icon: "activity" },
  { name: "Painting", icon: "brush" },
  { name: "Writing", icon: "pen-line" },
  { name: "Podcasts", icon: "mic" },
  { name: "Theater", icon: "drama" },
  { name: "Volunteering", icon: "hand-heart" },
  { name: "Gardening", icon: "flower-2" },
  { name: "Astronomy", icon: "telescope" },
  { name: "Cars", icon: "car" },
  { name: "Board Games", icon: "dice-5" },
  { name: "Chess", icon: "crown" },
  { name: "Karaoke", icon: "mic-2" },
  { name: "Stand-up Comedy", icon: "smile" },
  { name: "Spirituality", icon: "sun" },
  { name: "Science", icon: "flask-conical" },
  { name: "Languages", icon: "languages" },
  { name: "DIY", icon: "hammer" },
  { name: "Pets", icon: "paw-print" },
  { name: "Concerts", icon: "ticket" },
  { name: "Festivals", icon: "party-popper" },
  { name: "Road Trips", icon: "map" },
  { name: "Fine Dining", icon: "utensils-crossed" },
  { name: "Vegan", icon: "leaf" },
  { name: "Baking", icon: "cake-slice" },
  { name: "Investing", icon: "trending-up" },
  { name: "Museums", icon: "building-2" },
  { name: "Rock Climbing", icon: "mountain-snow" },
  { name: "Content Creation", icon: "video" },
  { name: "Blogging", icon: "notebook-pen" },
  { name: "Nightlife", icon: "moon" },
  { name: "Brunch", icon: "egg-fried" },
  { name: "Sustainability", icon: "recycle" },
  { name: "Philosophy", icon: "lightbulb" },
  { name: "Sci-Fi", icon: "rocket" },
  { name: "Fantasy", icon: "wand-sparkles" },
  { name: "K-Pop", icon: "star" },
  { name: "Hip Hop", icon: "headphones" },
  { name: "CrossFit", icon: "flame" },
  { name: "Martial Arts", icon: "sword" },
  { name: "Scuba Diving", icon: "anchor" },
  { name: "Backpacking", icon: "backpack" },
  { name: "Digital Nomad", icon: "laptop" },
  { name: "Startups", icon: "rocket" },
  { name: "AI", icon: "bot" },
  { name: "UX Design", icon: "layout" },
  { name: "Plant Parent", icon: "sprout" },
  { name: "Astrology", icon: "star-half" },
  { name: "Spa Days", icon: "bubbles" },
  { name: "Sneakers", icon: "footprints" },
  { name: "Cosplay", icon: "mask" },
  { name: "Tabletop RPG", icon: "dice-6" },
  { name: "Pottery", icon: "circle" },
  { name: "Street Art", icon: "paintbrush" },
  { name: "Escape Rooms", icon: "door-open" },
  { name: "Bowling", icon: "circle-dot" },
  { name: "Meal Prep", icon: "refrigerator" },
  { name: "Skincare", icon: "droplet" },
  { name: "Thrifting", icon: "shopping-bag" },
  { name: "Motorcycles", icon: "bike" },
  { name: "Paragliding", icon: "cloud" },
  { name: "Skydiving", icon: "plane-takeoff" },
  { name: "Mixology", icon: "martini" },
  { name: "Interior Design", icon: "lamp" },
  { name: "True Crime", icon: "search" },
  { name: "Horror", icon: "ghost" },
  { name: "Jazz", icon: "music-3" },
  { name: "EDM", icon: "audio-lines" },
  { name: "Pilates", icon: "stretch-horizontal" },
  { name: "Horse Riding", icon: "horse" },
  { name: "Van Life", icon: "bus" },
  { name: "Freelancing", icon: "wallet" },
  { name: "Open Source", icon: "github" },
  { name: "Bird Watching", icon: "bird" },
  { name: "Poetry", icon: "feather" },
  { name: "Mindfulness", icon: "circle" },
  { name: "Socializing", icon: "users" },
  { name: "Tea", icon: "cup-soda" },
  { name: "Craft Beer", icon: "glass-water" },
  { name: "Parenting", icon: "baby" },
  { name: "Architecture", icon: "building" },
  { name: "Sailing", icon: "sailboat" },
  { name: "Fishing", icon: "fish" },
  { name: "Skateboarding", icon: "circle-dot" },
  { name: "Esports", icon: "joystick" },
  { name: "Streaming", icon: "radio" },
  { name: "Self Improvement", icon: "arrow-up-circle" },
  { name: "Journaling", icon: "book-marked" },
  { name: "Comics", icon: "book-image" },
  { name: "K-Drama", icon: "clapperboard" },
  { name: "Bollywood", icon: "film" },
  { name: "Reggaeton", icon: "disc-3" },
  { name: "Classical", icon: "piano" },
  { name: "Country Music", icon: "guitar" },
  { name: "Boxing", icon: "swords" },
  { name: "Archery", icon: "crosshair" },
  { name: "Antiques", icon: "hourglass" },
  { name: "Collecting", icon: "gem" },
  { name: "Woodworking", icon: "axe" },
  { name: "Knitting", icon: "scissors" },
  { name: "Calligraphy", icon: "pen" },
  { name: "Puzzles", icon: "puzzle" },
  { name: "Minimalism", icon: "minus" },
  { name: "Activism", icon: "megaphone" },
  { name: "Psychology", icon: "brain-circuit" },
  { name: "History", icon: "landmark" },
  { name: "Real Estate", icon: "home" },
  { name: "Crypto", icon: "bitcoin" },
  { name: "Robotics", icon: "cog" },
  { name: "3D Printing", icon: "box" },
  { name: "Farm Life", icon: "tractor" },
  { name: "Smoothies", icon: "glass-water" },
  { name: "Hot Yoga", icon: "thermometer-sun" },
  { name: "Tattoos", icon: "pen-tool" },
  { name: "Watches", icon: "watch" },
  { name: "Jewelry", icon: "gem" },
  { name: "Urban Exploration", icon: "map-pin" },
  { name: "Paintball", icon: "target" },
  { name: "Darts", icon: "target" },
  { name: "Poker", icon: "spade" },
  { name: "Netflix", icon: "monitor-play" },
  { name: "Street Food", icon: "sandwich" },
  { name: "Makeup", icon: "sparkles" },
  { name: "Fashion Design", icon: "scissors" },
  { name: "Politics", icon: "landmark" },
  { name: "Wine Tasting", icon: "wine" },
  { name: "Beer Brewing", icon: "beer" },
  { name: "Home Workouts", icon: "house" },
  { name: "Sauna", icon: "bath" },
  { name: "Massage", icon: "hand" },
  { name: "Origami", icon: "origami" },
  { name: "Embroidery", icon: "needle" },
  { name: "Metalwork", icon: "wrench" },
  { name: "Glass Blowing", icon: "flame" },
  { name: "Sculpture", icon: "shapes" },
  { name: "Graffiti", icon: "spray-can" },
  { name: "Laser Tag", icon: "crosshair" },
  { name: "Billiards", icon: "circle-dot" },
  { name: "Fantasy Sports", icon: "bar-chart-3" },
  { name: "Magic", icon: "sparkle" },
  { name: "Tarot", icon: "cards" },
  { name: "LARP", icon: "sword" },
  { name: "Sudoku", icon: "grid-3x3" },
  { name: "Crosswords", icon: "grid-2x2" },
  { name: "Aquariums", icon: "shell" },
  { name: "Reptiles", icon: "turtle" },
  { name: "Astrophotography", icon: "moon-star" },
  { name: "Cooking Shows", icon: "tv-minimal-play" },
  { name: "Reality TV", icon: "tv-2" },
  { name: "Marvel", icon: "shield" },
  { name: "DC Comics", icon: "zap" },
  { name: "Chess Boxing", icon: "swords" },
  { name: "Ghost Hunting", icon: "ghost" },
  { name: "Piercings", icon: "circle" },
  { name: "Thrifting Fashion", icon: "shirt" },
];

async function main() {
  console.log("Seeding interests...");

  for (const interest of INTERESTS) {
    await prisma.interest.upsert({
      where: { name: interest.name },
      update: { icon: interest.icon },
      create: interest,
    });
  }

  console.log(`Seeded ${INTERESTS.length} interests.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
